FROM node:alpine

COPY . /app

RUN apk update \
    && apk add --virtual build-dependencies \
        build-base \
        gcc \
        wget \
        git \
        curl \
        bash \
        grep \
        --update nodejs npm

WORKDIR /app

RUN npm install

RUN npm install --silent --production \
    && apk del build-dependencies \
    && rm -rf /var/cache/apk/*

CMD ["sh", "-c", "npm run `echo ${ENV}`"]